import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/ui/nav";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Google+Sans:ital,opsz,wght@0,17..18,400..700;1,17..18,400..700" rel="stylesheet" />
      </head>
      <body
        className={`antialiased`}
      >
        <Nav />
        <div className="h-26"></div>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
